### ISSUE TITLE
How to create a Globus Application for basic example

### ISSUE THREAD

**Issue by zonca** [globus/globus-sdk-javascript#172]
I am trying to run the "basic" example:

https://github.com/globus/globus-sdk-javascript/tree/main/examples/basic

the README says "Create a Globus Application",
there are 5 types of Globus applications and each with a lot of settings.
I tried both with "science gateway" and "service API" but they both failed with different errors.

Can you please expand the docs?

**Comment by jbottigliero** [comment]
Hi @zonca – you'll need to create an OAuth public client, in the web application this is referred to as "Register a thick client or script that will be installed and run by users on their devices" – I'll update the documentation to reflect this.

Thanks for pointing this out!

<img width="675" alt="Screenshot 2024-05-16 at 8 39 24 AM" src="https://github.com/globus/globus-sdk-javascript/assets/694253/6c2f5225-e5c8-4134-9e98-5551255579a9">
