### ISSUE TITLE
Load data via Globus JS SDK, plot with Python

### ISSUE THREAD

**Issue by zonca** [globus/globus-sdk-javascript#175]
Inspired by @rpwagner's https://rpwagner.github.io/globus-sdk-javascript-ex-01/, here using `pandas` to parse JSON and make a plot via PyScript. Yes, I like Python.

https://zonca.github.io/globus-sdk-javascript-ex-01/

If useful I can clean it up and contribute a Pull Request to the examples.

**Comment by jbottigliero** [comment]
This is cool @zonca – I wasn't aware of PyScript, but can see how an example referencing it would be useful for the community. 

I'm going to add a section in our examples for community contributed examples and will include a reference to your repository (with your approval).

**Comment by rpwagner** [comment]
@jbottigliero, @zonca also wrote up a [short description of the demo](https://www.zonca.dev/posts/2024-05-16-globus-javascript-sdk-pyscript) if you want to link to that or share it elsewhere.
